default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DB_HOSTNAME"] || 'localhost' %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  port: <%= ENV["DB_PORT"] || 5432 %>

development:
  <<: *default
  database: elastic_practice_dev

test:
  <<: *default
  database: elastic_practice_test

production:
  <<: *default
  database: elastic_practice_production
